@php
    $yesNo = fn ($value) => $value === 'yes' ? 'Sí' : 'No';
    $label = fn ($value) => match ($value) { 'cash' => 'Efectivo', 'bank_transfer' => 'Transferencia', 'unspecified' => 'No especificada', default => '—' };
    $uses = ['residential' => 'Residencial', 'industrial' => 'Industrial', 'commercial' => 'Comercial', 'other' => 'Otro'];
    $partyName = fn ($party) => data_get($payload, $party.'.person.full_name') ?: data_get($payload, $party.'.person.legal_name') ?: '—';
@endphp
<div class="grid gap-5 md:grid-cols-2 text-sm">
    <section class="border rounded-lg p-4"><h4 class="font-semibold mb-2">Datos generales y propiedad</h4><dl class="space-y-1"><div>Referencia: {{ data_get($payload, 'metadata.contract_reference') ?: '—' }}</div><div>Fecha de firma: {{ data_get($payload, 'metadata.contract_date') ?: '—' }}</div><div>Alias: {{ data_get($payload, 'leased_property.alias') ?: '—' }}</div><div>Domicilio: {{ data_get($payload, 'leased_property.address') ?: '—' }}</div><div>Usos: {{ collect(data_get($payload, 'leased_property.property_use_codes', []))->map(fn ($use) => $uses[$use] ?? $use)->join(', ') ?: '—' }}</div></dl></section>
    <section class="border rounded-lg p-4"><h4 class="font-semibold mb-2">Partes</h4><dl class="space-y-1"><div>Arrendador: {{ $partyName('lessor') }}</div><div>Arrendatario: {{ $partyName('lessee') }}</div><div>Tercero / fiador: {{ data_get($payload, 'guarantor.type', 'none') }}</div><div>Fiador: {{ $partyName('guarantor') }}</div></dl></section>
    <section class="border rounded-lg p-4"><h4 class="font-semibold mb-2">Garantía, vigencia e importes</h4><dl class="space-y-1"><div>Inmueble en garantía: {{ $yesNo(data_get($payload, 'guarantee_property.exists')) }}</div>@if(data_get($payload, 'guarantee_property.exists') === 'yes')<div>Dirección garantía: {{ data_get($payload, 'guarantee_property.address') ?: '—' }}</div><div>Título: {{ data_get($payload, 'guarantee_property.title_deed') ?: '—' }}</div>@endif<div>Vigencia: {{ data_get($payload, 'term.start_date') ?: '—' }} a {{ data_get($payload, 'term.end_date') ?: '—' }}</div><div>Regla de pago: {{ data_get($payload, 'term.rent_due_rule.raw_text') ?: '—' }}</div><div>Renta mensual: {{ data_get($payload, 'amounts.monthly_rent') ?? '—' }}</div><div>Depósito: {{ data_get($payload, 'amounts.security_deposit') ?? '—' }}</div><div>Comisión mensual: {{ data_get($payload, 'amounts.monthly_commission_value') ?? '—' }} ({{ data_get($payload, 'amounts.monthly_commission_unit') }})</div></dl></section>
    <section class="border rounded-lg p-4"><h4 class="font-semibold mb-2">Pago, mantenimiento y renovación</h4><dl class="space-y-1"><div>Método: {{ $label(data_get($payload, 'payment.method')) }}</div>@if(data_get($payload, 'payment.method') === 'bank_transfer')<div>Banco: {{ data_get($payload, 'payment.bank_name') ?: '—' }}</div><div>Beneficiario: {{ data_get($payload, 'payment.beneficiary') ?: '—' }}</div><div>CLABE: {{ data_get($payload, 'payment.clabe') ?: '—' }}</div>@endif<div>Mantenimiento: {{ $yesNo(data_get($payload, 'maintenance.exists')) }}</div>@if(data_get($payload, 'maintenance.exists') === 'yes')<div>Pagador: {{ data_get($payload, 'maintenance.payer') ?: '—' }}</div>@endif<div>Renovación: {{ $yesNo(data_get($payload, 'renewal.is_renewal')) }}</div>@if(data_get($payload, 'renewal.is_renewal') === 'yes')<div>Contrato previo: {{ data_get($payload, 'renewal.previous_contract_id') ?: '—' }}</div>@endif</dl></section>
    <section class="border rounded-lg p-4 md:col-span-2"><h4 class="font-semibold mb-2">Conciliación actual</h4><div class="grid gap-2 md:grid-cols-3"><div>Cliente: {{ $draft->cliente?->nombre ?? 'No vinculado' }}</div><div>Propiedad: {{ $draft->propiedad?->alias ?? 'No vinculada' }}</div><div>Inquilino: {{ $draft->inquilino?->nombre ?? 'No vinculado' }}</div></div></section>
</div>
