<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-xl text-gray-800">Captura de contrato — borrador #{{ $draft->id }}</h2><p class="text-sm text-orange-700">Borrador — no publicado</p></div><a href="{{ route('contratos.borradores.show', $draft) }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-lg">Guardar y salir</a></div></x-slot>
    <div class="max-w-6xl mx-auto mt-6 space-y-5">
        <nav class="bg-white rounded-lg shadow p-4 flex flex-wrap gap-2 text-sm">@foreach($steps as $key => $label)<a href="{{ route('contratos.borradores.wizard.show', [$draft, $key]) }}" class="rounded px-2 py-1 {{ $step === $key ? 'bg-blue-600 text-white font-semibold' : 'bg-gray-100 text-gray-700' }}">{{ $loop->iteration }}. {{ $label }}</a>@endforeach</nav>
        @if($errors->has('expected_version_id'))<div class="rounded border border-orange-300 bg-orange-50 p-4 text-sm text-orange-800">{{ $errors->first('expected_version_id') }}</div>@endif
        @if($step === 'resumen')
            <div class="bg-white rounded-lg shadow p-5"><h3 class="font-semibold text-lg mb-3">Resumen del borrador</h3><p class="text-sm text-gray-600 mb-4">Esta revisión es informativa. No publica ni genera documentos.</p>@include('contratos.borradores._wizard_summary', ['payload' => $payload, 'draft' => $draft])</div>
        @else
            <form method="POST" action="{{ route('contratos.borradores.wizard.save', [$draft, $step]) }}" class="bg-white rounded-lg shadow p-6 space-y-6">@csrf @method('PUT')<input type="hidden" name="expected_version_id" value="{{ $draft->currentVersion->id }}">
                <h3 class="font-semibold text-lg">{{ $steps[$step] }}</h3>
                @if($step === 'generales')
                    <div class="grid gap-4 md:grid-cols-2"><div><label class="block text-sm font-medium">Referencia interna</label><input name="payload[metadata][contract_reference]" value="{{ data_get($payload, 'metadata.contract_reference') }}" class="mt-1 w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium">Fecha de firma</label><input type="date" name="payload[metadata][contract_date]" value="{{ data_get($payload, 'metadata.contract_date') }}" class="mt-1 w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium">Alias del inmueble</label><input name="payload[leased_property][alias]" value="{{ data_get($payload, 'leased_property.alias') }}" class="mt-1 w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium">Domicilio del inmueble</label><input name="payload[leased_property][address]" value="{{ data_get($payload, 'leased_property.address') }}" class="mt-1 w-full border rounded px-3 py-2"></div></div>
                @elseif(in_array($step, ['arrendador', 'arrendatario'], true))
                    @include('contratos.borradores._wizard_party', ['party' => $step === 'arrendador' ? 'lessor' : 'lessee', 'payload' => $payload])
                @elseif($step === 'tercero')
                    @php($guarantor = data_get($payload, 'guarantor', []))
                    <div><label class="block text-sm font-medium">Tipo de tercero</label><select id="guarantor-type" name="payload[guarantor][type]" class="mt-1 w-full border rounded px-3 py-2"><option value="none" @selected(data_get($guarantor, 'type') === 'none')>Sin tercero</option><option value="fisica" @selected(data_get($guarantor, 'type') === 'fisica')>Persona física</option><option value="moral" @selected(data_get($guarantor, 'type') === 'moral')>Persona moral</option></select></div>
                    <div data-guarantor-fields class="mt-5">@include('contratos.borradores._wizard_party', ['party' => 'guarantor', 'payload' => array_merge($payload, ['guarantor' => ['person' => data_get($guarantor, 'person', []), 'representative' => data_get($guarantor, 'representative', [])]])])</div>
                @elseif($step === 'garantia')
                    <div><label class="block text-sm font-medium">¿Existe inmueble en garantía?</label><select data-guarantee-exists name="payload[guarantee_property][exists]" class="mt-1 w-full border rounded px-3 py-2"><option value="no" @selected(data_get($payload, 'guarantee_property.exists') === 'no')>No</option><option value="yes" @selected(data_get($payload, 'guarantee_property.exists') === 'yes')>Sí</option></select></div><div data-guarantee-fields class="grid gap-4 md:grid-cols-2 mt-4"><div><label class="block text-sm font-medium">Domicilio</label><input name="payload[guarantee_property][address]" value="{{ data_get($payload, 'guarantee_property.address') }}" class="mt-1 w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium">Título de propiedad</label><input name="payload[guarantee_property][title_deed]" value="{{ data_get($payload, 'guarantee_property.title_deed') }}" class="mt-1 w-full border rounded px-3 py-2"></div></div>
                @elseif($step === 'vigencia')
                    <div class="grid gap-4 md:grid-cols-2">@foreach(['start_date' => 'Inicio', 'end_date' => 'Fin'] as $field => $label)<div><label class="block text-sm font-medium">{{ $label }}</label><input type="date" name="payload[term][{{ $field }}]" value="{{ data_get($payload, 'term.'.$field) }}" class="mt-1 w-full border rounded px-3 py-2"></div>@endforeach<div><label class="block text-sm font-medium">Duración</label><input name="payload[term][duration_label]" value="{{ data_get($payload, 'term.duration_label') }}" class="mt-1 w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium">Regla de pago (literal)</label><input name="payload[term][rent_due_rule][raw_text]" value="{{ data_get($payload, 'term.rent_due_rule.raw_text') }}" placeholder="05 a 10" class="mt-1 w-full border rounded px-3 py-2"></div>@foreach(['total_rent' => 'Renta total', 'monthly_rent' => 'Renta mensual', 'security_deposit' => 'Depósito', 'rental_commission' => 'Comisión por renta', 'monthly_commission_value' => 'Comisión mensual'] as $field => $label)<div><label class="block text-sm font-medium">{{ $label }}</label><input inputmode="decimal" name="payload[amounts][{{ $field }}]" value="{{ data_get($payload, 'amounts.'.$field) }}" class="mt-1 w-full border rounded px-3 py-2"></div>@endforeach<div><label class="block text-sm font-medium">Unidad de comisión mensual</label><select name="payload[amounts][monthly_commission_unit]" class="mt-1 w-full border rounded px-3 py-2">@foreach(['unknown' => 'No especificada', 'percent' => 'Porcentaje', 'fraction' => 'Fracción', 'fixed' => 'Importe fijo'] as $value => $label)<option value="{{ $value }}" @selected(data_get($payload, 'amounts.monthly_commission_unit') === $value)>{{ $label }}</option>@endforeach</select></div></div>
                @elseif($step === 'uso')
                    <input type="hidden" name="payload[leased_property][_property_use_codes_submitted]" value="1"><div class="flex flex-wrap gap-4">@foreach(['residential' => 'Residencial', 'industrial' => 'Industrial', 'commercial' => 'Comercial', 'other' => 'Otro'] as $value => $label)<label><input type="checkbox" name="payload[leased_property][property_use_codes][]" value="{{ $value }}" @checked(in_array($value, data_get($payload, 'leased_property.property_use_codes', []), true))> {{ $label }}</label>@endforeach</div>
                @elseif($step === 'pago')
                    <div><label class="block text-sm font-medium">Forma de pago</label><select data-payment-method name="payload[payment][method]" class="mt-1 w-full border rounded px-3 py-2">@foreach(['unspecified' => 'No especificada', 'cash' => 'Efectivo', 'bank_transfer' => 'Transferencia'] as $value => $label)<option value="{{ $value }}" @selected(data_get($payload, 'payment.method') === $value)>{{ $label }}</option>@endforeach</select></div><div data-bank-fields class="grid gap-4 md:grid-cols-3 mt-4">@foreach(['bank_name' => 'Banco', 'beneficiary' => 'Beneficiario', 'clabe' => 'CLABE'] as $field => $label)<div><label class="block text-sm font-medium">{{ $label }}</label><input name="payload[payment][{{ $field }}]" value="{{ data_get($payload, 'payment.'.$field) }}" class="mt-1 w-full border rounded px-3 py-2"></div>@endforeach</div>
                @elseif($step === 'mantenimiento')
                    <div><label class="block text-sm font-medium">¿Existen cuotas?</label><select data-maintenance-exists name="payload[maintenance][exists]" class="mt-1 w-full border rounded px-3 py-2"><option value="no" @selected(data_get($payload, 'maintenance.exists') === 'no')>No</option><option value="yes" @selected(data_get($payload, 'maintenance.exists') === 'yes')>Sí</option></select></div><div data-maintenance-payer class="mt-4"><label class="block text-sm font-medium">Quién paga</label><select name="payload[maintenance][payer]" class="mt-1 w-full border rounded px-3 py-2"><option value="">—</option><option value="lessor" @selected(data_get($payload, 'maintenance.payer') === 'lessor')>Arrendador</option><option value="lessee" @selected(data_get($payload, 'maintenance.payer') === 'lessee')>Arrendatario</option></select></div>
                @elseif($step === 'renovacion')
                    <div><label class="block text-sm font-medium">¿Es renovación?</label><select data-renewal name="payload[renewal][is_renewal]" class="mt-1 w-full border rounded px-3 py-2"><option value="no" @selected(data_get($payload, 'renewal.is_renewal') === 'no')>No</option><option value="yes" @selected(data_get($payload, 'renewal.is_renewal') === 'yes')>Sí</option></select></div><div data-renewal-fields class="mt-4"><label class="block text-sm font-medium">Contrato previo (ID opcional)</label><input inputmode="numeric" name="payload[renewal][previous_contract_id]" value="{{ data_get($payload, 'renewal.previous_contract_id') }}" class="mt-1 w-full border rounded px-3 py-2"></div>
                @endif
                <div class="flex flex-wrap gap-3 pt-3"><button type="submit" class="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-lg">Guardar este paso</button><button type="submit" name="next" value="1" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg">Guardar y continuar</button><button type="submit" name="exit" value="1" class="bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold py-2 px-4 rounded-lg">Guardar y salir</button></div>
            </form>
        @endif
    </div>
    <script>document.addEventListener('DOMContentLoaded',function(){function toggle(selector,show){document.querySelectorAll(selector).forEach(function(el){el.classList.toggle('hidden',!show);});}function party(){document.querySelectorAll('[data-party-type]').forEach(function(s){var update=function(){document.querySelectorAll('[data-party-branch="'+s.dataset.party+'"]').forEach(function(el){el.classList.toggle('hidden',el.dataset.type!==s.value);});};s.addEventListener('change',update);update();});}party();var g=document.getElementById('guarantor-type');if(g){var u=function(){var personType=document.querySelector('[data-party-type="guarantor"]');if(personType&&g.value!=='none'){personType.value=g.value;personType.dispatchEvent(new Event('change'));}toggle('[data-guarantor-fields]',g.value!=='none');};g.addEventListener('change',u);u();}var guarantee=document.querySelector('[data-guarantee-exists]');if(guarantee){var gu=function(){toggle('[data-guarantee-fields]',guarantee.value==='yes');};guarantee.addEventListener('change',gu);gu();}var payment=document.querySelector('[data-payment-method]');if(payment){var pu=function(){toggle('[data-bank-fields]',payment.value==='bank_transfer');};payment.addEventListener('change',pu);pu();}var maintenance=document.querySelector('[data-maintenance-exists]');if(maintenance){var mu=function(){toggle('[data-maintenance-payer]',maintenance.value==='yes');};maintenance.addEventListener('change',mu);mu();}var renewal=document.querySelector('[data-renewal]');if(renewal){var ru=function(){toggle('[data-renewal-fields]',renewal.value==='yes');};renewal.addEventListener('change',ru);ru();}});</script>
</x-app-layout>
